config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }

  resources :users, only: [:show, :edit, :update]

  resources :usages, only: [:index]

  resources :games, only: [:show] do
    member do
      post 'execute_command' # コマンド実行用のルート
      post 'escape'          # 逃げるアクションのルート
      get 'result'           
    end
  end

  post 'start_game', to: 'games#start_game' # ゲーム開始用のルート


  resources :posts do
    resources :comments do
      collection do
        get 'latest'  # これにより /posts/:post_id/comments/latest のルートが作成されます
      end
    end
    collection do
      get 'search'
      get 'latest'
    end
  end

  resources :direct_message_requests, only: [:create] do
    member do
      patch :approve
      patch :reject
    end
  end
  
  # 既存のnotificationsに追加
  resources :notifications, only: [] do
    member do
      patch 'mark_as_read'
    end
    collection do
      patch 'approval', to: 'notifications#create_approval_notification'
      patch 'rejection', to: 'notifications#create_rejection_notification'
    end
  end

  resources :rooms do
    resources :messages, only: [:create] # ここで messages リソースをネスト
  end


  root to: "posts#index"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:google_oauth2]
  belongs_to :level
  has_many :sns_credentials
  has_many :posts
  has_many :comments
  has_many :room_users
  has_many :rooms, through: :room_users
  has_many :messages, foreign_key: :sender_id
  has_many :direct_message_requests, dependent: :destroy
  has_many :notifications, dependent: :destroy
  has_many :user_skills
  has_many :skills, through: :user_skills
  has_many :user_characters
  has_many :characters, through: :user_characters
  has_many :status_effects, dependent: :destroy
  has_many :games


   # 初期レベル0を設定するメソッド
   after_create :set_initial_level

  def add_experience(points)
    self.experience_points += points
    level_up if experience_points >= current_level.exp_required
    save
  end
  
  def level_up
    ActiveRecord::Base.transaction do
      while experience_points >= current_level&.exp_required
        # 経験値とレベルを更新
        self.experience_points -= current_level.exp_required
        self.level_id = next_level.id
        
        # ステータスを更新
        self.max_hp += current_level.hp_increase
        self.hp = self.max_hp
        self.offense_power += current_level.offense_increase
        self.defense_power += current_level.defense_increase
        self.luck += current_level.luck_increase
        self.speed += current_level.speed_increase
        self.status_points += current_level.status_point_increase  # 修正箇所
  
        # 報酬のアンロックと通知の保存
        unlock_rewards_for_level(current_level)
        save_level_up_notification(current_level)
      end
  
      # 変更を全て保存
      raise ActiveRecord::Rollback unless save # 保存に失敗した場合はロールバック
    end
  rescue => e
    Rails.logger.error("Failed to level up user: #{e.message}")
  end
  

  def save_level_up_notification(level)
    message = "Lv.#{level.level_number}になりました！"

    # 通知をデータベースに保存
    notifications.create(
      message: message,
      notification_type: "level_up",
      next_experience_point: level.exp_required,
      required_comment_count: level.exp_required / 5,
      skill_get_message: level.reward_value.present? && level.reward_type == "skill" ? "新しいスキル「#{level.reward_value}」を獲得しました！" : "",
      item_get_message: level.reward_value.present? && level.reward_type == "item" ?  "新しいアイテム「#{level.reward_value}」を獲得しました！" : ""
    )

  end

  def unlock_rewards_for_level(level)
    case level.reward_type
    when 'skill'
      unlock_skill(level.reward_value)
      LevelUpNotificationChannel.broadcast_to(self, {
        level_up_message: "レベル#{level.level_number}に到達しました！",
        skill_get_message: "新しいスキル「#{level.reward_value}」を獲得しました！",
        next_experience_point: "次のレベルに必要な経験値: #{level.exp_required}",
        required_comment_count: "必要最低コメント数(目安): #{level.exp_required / 5}"
      })
    when 'item'
      unlock_item(level.reward_value)
      LevelUpNotificationChannel.broadcast_to(self, {
        level_up_message: "レベル#{level.level_number}に到達しました！",
        item_get_message: "新しいアイテム「#{level.reward_value}」を獲得しました！",
        next_experience_point: "次のレベルに必要な経験値: #{level.exp_required}",
        required_comment_count: "必要最低コメント数(目安): #{level.exp_required / 5}"
      })
    else
      LevelUpNotificationChannel.broadcast_to(self, {
        level_up_message: "レベル#{level.level_number}に到達しました！",
        next_experience_point: "次のレベルに必要な経験値: #{level.exp_required}",
        required_comment_count: "必要最低コメント数(目安): #{level.exp_required / 5}"
      })
    end
  end

  def unlock_skill(skill_name)
    # Skillが存在するか確認し、なければ作成
    skill = Skill.find_or_initialize_by(name: skill_name)
  
    if skill.new_record?
      skill.user_id = self.id # user_idが設定されるようにする
      skill.save
    end
  
    # ユーザーとスキルの関連付けを中間テーブルに作成
    self.skills << skill unless self.skills.include?(skill)
  end
  

  def unlock_item(item_name)
    # アイテムをユーザーに付与する処理
    items.create(name: item_name)
  end

  def current_level
    Level.find(level_id) # 現在のレベルを取得
  end
  
  def next_level
    Level.where("level_number > ?", current_level.level_number).order(:level_number).first || current_level
  end

  def recover_hp(amount)
    self.hp += amount
    self.hp = [self.hp, max_hp].min # 最大HPを超えないようにする
    save
  end

  def decrease_hp(amount)
    self.hp -= amount
    self.hp = [self.hp, 0].max # HPが0未満にならないようにする
    save
  end
  
  

  def guest?
    email == 'guest@example.com'
  end

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.nickname = 'ゲスト'
      user.password = SecureRandom.urlsafe_base64 # ゲスト用のパスワード
      user.password_confirmation = user.password
    end
  end

  def self.from_omniauth(auth)
    sns = SnsCredential.where(provider: auth.provider, uid: auth.uid).first_or_create
    user = User.where(email: auth.info.email).first_or_initialize(
      nickname: auth.info.name,
      email: auth.info.email
    )
    if user.persisted?
      sns.user = user
      sns.save
    end
    user
  end

  private

  def set_initial_level
    self.level = Level.find_by(level_number: 0) # レベル0を初期設定
    self.hp = 3
    self.max_hp = 3
    save
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  def google_oauth2
    authorization
  end
  
   private
  
  def authorization
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted? #ユーザー情報が登録済みなので、新規登録ではなくログイン処理を行う
      sign_in_and_redirect @user, event: :authentication
    else #ユーザー情報が未登録なので、新規登録画面へ遷移する
      render template: 'devise/registrations/new'
    end
  end
  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    if params[:sns_auth] == 'true'
      pass = Devise.friendly_token
      params[:user][:password] = pass
      params[:user][:password_confirmation] = pass
    end
    super
  end 

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end
  # 
  ## 例: SessionsController
def create
  user = User.find_by(email: params[:email])
  if user&.authenticate(params[:password])
    cookies.signed[:user_id] = user.id
    redirect_to root_path
  else
    flash[:alert] = "Invalid email or password"
    render :new
  end
end


  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def show
    @user = User.find(params[:id]) # URLのパラメータからユーザーを取得
    @is_guest = guest_user?(@user) # ユーザーがゲストかどうかを判定
    @posts = @user.posts.order(created_at: :desc) # ユーザーの投稿を取得
    @from_nickname = params[:from] == 'nickname'
    sender_id = current_user.id
    receiver_id = @user.id
    @existing_request = DirectMessageRequest.find_by(sender_id: sender_id, receiver_id: receiver_id)
    
    # ユーザーが参加しているDMルームとグループルームを取得
    @dm_rooms = @user.rooms.where(is_group: false)
    @group_rooms = @user.rooms.where(is_group: true)

    # 各DMルームの最後のメッセージを取得
    @last_messages = {}
    @dm_rooms.each do |room|
      @last_messages[room.id] = room.messages.order(created_at: :desc).first
    end

    # ユーザーの通知を取得
    @notifications = Notification.where(user: @user).order(created_at: :desc)
  end

  def edit
    @user = current_user # URLのパラメータからユーザーを取得
  end

  def update
    @user = current_user
    if @user.update(user_params)
      redirect_to @user, notice: 'プロフィールが更新されました。'
    else
      render :edit
    end
  end


  private

  def guest_user?(user)
    # ユーザーがゲストかどうかを判定するロジック
    user.guest?
  end

  def user_params
    params.require(:user).permit(:nickname, :thought, :profile_image)
  end
 
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<body class="edit-profile-body">

  <%= link_to 'マイページに戻る', user_path(current_user), class: "post-top-button" %>

  <div class="edit-profile-container">
    <div class="edit-profile-wrapper">
      <%= form_with(model: @user, local: true, class: "edit-profile-form") do |form| %>
      <%= form.hidden_field :profile_image, id: "selected-profile-image" %>

        <div class="edit-profile-upper-wrapper">

          <div class="edit-profile-user-image-box">

            <div class="edit-profile-user-image-description">
              プロフィール画像
            </div>

            <div class="edit-profile-user-image">
            </div>

          </div>

          <div class="edit-profile-user-detail">
        
            <div class="edit-profile-user-name">
              <%= form.label :nickname, "ニックネーム", class: "edit-profile-label" %>
              <%= form.text_field :nickname, class: "edit-profile-text-field" %>
            </div>

            <div class="edit-profile-user-thought">
              <%= form.label :thought, "ひとこと", class: "edit-profile-label"%>
              <%= form.text_field :thought, class: "edit-profile-text-field" %>
            </div>

          </div>

        </div>

        <div class="edit-profile-downer-wrapper">
          <button class="scroll-button left" type="button">&#9664;</button>

          <div class="edit-profile-image-container">

            <div class="edit-profile-image-box">

              <div class="upper-profile-image">
                <%= image_tag 'postman2.png', alt: 'お知らせのイメージ'%>
                <%= image_tag 'tebukurodispatch2.png', alt: '手袋ディスパッチ（キャラクター）' %>
                 <%= image_tag 'h-twins-gals.png', alt: '設定のイメージ' %>
                  <%= image_tag 'engranaje.png', alt: '設定のイメージ' %>
                   <%= image_tag 'engranaje.png', alt: '設定のイメージ' %>
                    <%= image_tag 'engranaje.png', alt: '設定のイメージ' %>
                     <%= image_tag 'engranaje.png', alt: '設定のイメージ' %>
                      <%= image_tag 'engranaje.png', alt: '設定のイメージ' %>
                <%= image_tag 'engranaje.png', alt: '設定のイメージ' %>
                 <%= image_tag 'engranaje.png', alt: '設定のイメージ' %>
                  <%= image_tag 'engranaje.png', alt: '設定のイメージ' %>
                   <%= image_tag 'engranaje.png', alt: '設定のイメージ' %>
                    <%= image_tag 'engranaje.png', alt: '設定のイメージ' %>
                     <%= image_tag 'engranaje.png', alt: '設定のイメージ' %>
                      <%= image_tag 'engranaje.png', alt: '設定のイメージ' %>
              </div>

              
              <div class="downer-profile-image">
                <%= image_tag 'engranaje.png', alt: '設定のイメージ' %>
                 <%= image_tag 'engranaje.png', alt: '設定のイメージ' %>
                  <%= image_tag 'engranaje.png', alt: '設定のイメージ' %>
                   <%= image_tag 'engranaje.png', alt: '設定のイメージ' %>
                    <%= image_tag 'engranaje.png', alt: '設定のイメージ' %>
                     <%= image_tag 'engranaje.png', alt: '設定のイメージ' %>
                      <%= image_tag 'engranaje.png', alt: '設定のイメージ' %>
                      <%= image_tag 'engranaje.png', alt: '設定のイメージ' %>
                 <%= image_tag 'engranaje.png', alt: '設定のイメージ' %>
                  <%= image_tag 'engranaje.png', alt: '設定のイメージ' %>
                   <%= image_tag 'engranaje.png', alt: '設定のイメージ' %>
                    <%= image_tag 'engranaje.png', alt: '設定のイメージ' %>
                     <%= image_tag 'engranaje.png', alt: '設定のイメージ' %>
                      <%= image_tag 'engranaje.png', alt: '設定のイメージ' %>
                       <%= image_tag 'engranaje.png', alt: '設定のイメージ' %>
              </div>

            </div>

          </div>

          <button class="scroll-button right" type="button">&#9654;</button>
        </div>

        <div class="edit-profile-button-box">
          <%= form.submit "更新", class: "edit-profile-button"%>
        </div>

      <% end %>
    </div>
  </div>

</body>

app/views/users/show.html.erb
<% if @from_nickname %>
  <body class="other-user-show-page">
    <div class="back-to-top">
      <%= link_to "Top画面へ", root_path, class: "post-top-button" %>
    </div>

    <div class="profile-container-from-other-user-view">
      <div class="profile-wrapper-from-other-user-view">
        <% if user_signed_in? && !@is_guest && @user.id != current_user.id%>
          <%= image_tag 'dmpot2.png', alt: 'ダイレクトメッセージのイメージ', class: "direct-message-image", data: { user_id: @user.id } %>
          <div class="direct-message-box">
            <div class="direct-message-start">
              <% if @existing_request %>
                <span id="direct-message-text">申請済</span>
              <% else %>
                <span id="direct-message-text"><%= "#{@user.nickname}に話しかけますか？" %></span>
                <div id="direct-message-actions">
                  <div class="direct-message-yes-or-no">
                    <button class="direct-message-yes">yes</button>
                    <button class="direct-message-no">no</button>
                  </div>
                </div>
              <% end %>
            </div>
          </div>
        <% end %>

        <div class="profile-box">
          <div class="profile-image">
            <%= image_tag(@user.profile_image.present? ? @user.profile_image : 'default_profile_image.png') %>
          </div>
          <%= @user.nickname %>
          Lv.<%= @user.current_level.level_number %>
        </div>

        <div class="profile-detail">
          <label class="user-one-liner">ひとこと</label>
          <div class="profile-user-one-liner">
            <%= @user.thought%>
          </div>
        </div>
      </div>
    </div>
  </body>
<% else %>
  <body class="user-show-page">
    <div class="back-to-top">
      <%= link_to "Top画面へ", root_path, class: "post-top-button" %>
    </div>

    <div class="profile-container">
      <div class="profile-wrapper">
        <% if @user.notifications.any? { |notification| !notification.read }%>
          <%= image_tag 'postman-reaction.png', alt: 'お知らせのイメージ', class: "notification-image", data: { user_id: @user.id } %>
        <% else %>
          <%= image_tag 'postman2.png', alt: 'お知らせのイメージ', class: "notification-image", data: { user_id: @user.id } %>
        <% end %>
        <%= image_tag 'engranaje.png', alt: '設定のイメージ', class: "settings-image" %>

        <div class="profile-box">
          <div class="profile-image">
            <%= image_tag(@user.profile_image.present? ? @user.profile_image : 'default_profile_image.png') %>
          </div>
          <div class="profile-user-name">
            <%= @user.nickname %>
          </div>
          Lv.<%= @user.current_level.level_number %>
          <div class="edit-profile-box">
            <%= link_to "プロフィール変更", edit_user_path(@user), class: "edit-profile" %>
          </div>
        </div>

        <div class="profile-detail">
          <label class="user-one-liner">ひとこと</label>
          <div class="profile-user-one-liner">
            <%= @user.thought%>
          </div>
        </div>
      </div>
    </div>

    <div class="post-direct-message-collection-box">
      <div class="post-direct-message-collection-buttons">
        <button class="users-post-list-button">投稿一覧</button>
        <button class="direct-message-list-button">DM一覧</button>
        <button class="character-collection-list-button">バケモン図鑑</button>
        <button class="item-list-button" style="display:none;">アイテム一覧</button>
      </div>

      <div class="lists-container">
        <div class="my-posts-list" id="my-posts-list-display">
          <% @posts.limit(30).each do |post| %>
            <div class="post">
              <h3><%= link_to post.title, post_path(post, from: 'mypage') %></h3>
              <p><%= truncate(post.content, length: 100) %></p>
            </div>
          <% end %>
        </div>

        <div class="my-dm-list" style="display: none;" id="my-dm-list-display">
          <div class="dm-list-descriptions">
            <div class="dm-partner-name-description">
              チャット相手
            </div>
            <div class="dm-last-message-description">
              メッセージ
            </div>
          </div>

          <% @dm_rooms.each do |room| %>
            <div class="my-dm-box">
              <div class="dm-partner-name">
                <% room.users.each do |participant| %>
                  <% if participant != @user %>
                    <!-- DMの相手のニックネームを表示 -->
                    <%= participant.nickname %>
                  <% end %>
                <% end %>
              </div>
              <div class="dm-start-box">
                <div class="dm-last-message">
                  <% if @last_messages[room.id] %>
                    <p><%= @last_messages[room.id].content %></p>
                  <% else %>
                    <p>まだメッセージがありません</p>
                  <% end %>
                </div>
                <div class="start-dm">
                  <%= link_to 'DMを開く', room_path(room), class: "start-dm-button", style: "display: none;" %>
                </div>
              </div>
            </div>
          <% end %>
        </div>



        <div class="my-character-collection-list" style="display: none;" id="my-character-collection-list">
          <div class="character-lists">
            <div class="character-container">
              <div class="characters-wrapper">
                <div class="characters characters1">
                  <div class="character">No.1
                    <%= image_tag 'small-h-twins-gals.png', alt: 'iwanttobeGのキャラクターイメージ', class: "character-image" %>
                  </div>
                  <div class="character">No.2</div>
                  <div class="character">No.3</div>
                  <div class="character">No.4</div>
                  <div class="character">No.5</div>
                  <div class="character">No.6</div>
                  <div class="character">No.7</div>
                </div>

                <div class="characters characters2">
                  <div class="character">No.8</div>
                  <div class="character">No.9</div>
                  <div class="character">No.10</div>
                  <div class="character">No.11</div>
                  <div class="character">No.12</div>
                  <div class="character">No.13</div>
                  <div class="character">No.14</div>
                </div>

                <div class="characters characters3">
                  <div class="character">No.15</div>
                  <div class="character">No.16</div>
                  <div class="character">No.17</div>
                  <div class="character">No.18</div>
                  <div class="character">No.19</div>
                  <div class="character">No.20</div>
                  <div class="character">No.21</div>
                </div>

                <div class="characters characters4">
                  <div class="character">No.22</div>
                  <div class="character">No.23</div>
                  <div class="character">No.24</div>
                  <div class="character">No.25</div>
                  <div class="character">No.26</div>
                  <div class="character">No.27</div>
                  <div class="character">No.28</div>
                </div>

                <div class="characters characters5">
                  <div class="character">No.29</div>
                  <div class="character">No.30</div>
                  <div class="character">No.31</div>
                  <div class="character">No.32</div>
                  <div class="character">No.33</div>
                  <div class="character">No.34</div>
                  <div class="character">No.35</div>
                </div>

                <div class="characters characters6">
                  <div class="character">No.36</div>
                  <div class="character">No.37</div>
                  <div class="character">No.38</div>
                  <div class="character">No.39</div>
                  <div class="character">No.40</div>
                  <div class="character">No.41</div>
                  <div class="character">No.42</div>
                </div>

                <div class="characters characters7">
                  <div class="character">No.43</div>
                  <div class="character">No.44</div>
                  <div class="character">No.45</div>
                  <div class="character">No.46</div>
                  <div class="character">No.47</div>
                  <div class="character">No.48</div>
                  <div class="character">No.49</div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

<div class="notification-modal" style="display: none;">
  <div class="notification-modal-content">
    <h2>通知一覧</h2>
    <div class="notification-content-box">
    <ul>
      <% @notifications.each do |notification| %>
        <li class="<%= notification.read ? 'read' : 'unread' %>">
          <% if notification.notification_type == 'dm_request' %>
            <%= "DMリクエスト: #{notification.message}" %>
            <br>
            <% # リクエストのIDを取得してリンクに追加する %>
            <% request_id = notification.direct_message_request_id %> <!-- 修正: request_id を直接取得 -->
            <%= link_to '承認', approve_direct_message_request_path(request_id), method: :patch, class: 'approve-request-button', data: { id: request_id } %>
            <%= link_to '拒否', reject_direct_message_request_path(request_id), method: :patch, class: 'reject-request-button', data: { id: request_id } %>
          <% end %>
          <% if notification.notification_type == 'level_up' %>
            <%= "レベルアップ！: #{notification.message}" %>
            <p>次のレベルまでの経験値: <%= notification.next_experience_point %></p>
            <p>必要最低コメント数(目安): <%= notification.required_comment_count %></p>
            <p>獲得スキル: <%= notification.skill_get_message%></p>
            <p>獲得アイテム: <%= notification.item_get_message%></p>
          <% end %>
          <%# <% unless notification.read %>
            <%# <%= link_to '既読', mark_as_read_notification_path(notification), method: :patch, remote: true %>
          <%# <% end %> 
        </li>
      <% end %>
    </ul>
    </div>
  </div>
</div>

  </body>
<% end %>