config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }

  resources :users, only: [:show, :edit, :update]

  resources :usages, only: [:index]

  resources :games, only: [:show] do
    member do
      post 'execute_command' # コマンド実行用のルート
      post 'escape'          # 逃げるアクションのルート
      get 'result'           
    end
  end

  post 'start_game', to: 'games#start_game' # ゲーム開始用のルート


  resources :posts do
    resources :comments do
      collection do
        get 'latest'  # これにより /posts/:post_id/comments/latest のルートが作成されます
      end
    end
    collection do
      get 'search'
      get 'latest'
    end
  end

  resources :direct_message_requests, only: [:create] do
    member do
      patch :approve
      patch :reject
    end
  end
  
  # 既存のnotificationsに追加
  resources :notifications, only: [] do
    member do
      patch 'mark_as_read'
    end
    collection do
      patch 'approval', to: 'notifications#create_approval_notification'
      patch 'rejection', to: 'notifications#create_rejection_notification'
    end
  end

  resources :rooms do
    resources :messages, only: [:create] # ここで messages リソースをネスト
  end


  root to: "posts#index"
end

app/views/shared/_footer.html.erb
<footer>
  <div class="site-detail">
  <ul>
    <li><a href="#">About</a></li>
    <li><a href="#">サイトマップ</a></li>
    <li><a href="#">プライバシーポリシー</a></li>
  </ul>
  </div>
  <div class="copyright">© 2024 Example Inc. All Rights Reserved.</div>
</footer>

app/views/shared/_header.html.erb
<nav class="navbar">
  <div class="navbar-logo">
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 582.5 125">
      <defs>
        <style>
          .cls-1 { letter-spacing: .3em; }
          .cls-2 { font-family: DotGothic16-Regular, DotGothic16; font-size: 125px; }
          .cls-3 { letter-spacing: -.26em; }
          .cls-4 { letter-spacing: -.1em; }
          .cls-5 { letter-spacing: -.18em; }
          .cls-6 { letter-spacing: -.12em; }
          .cls-7 { letter-spacing: .06em; }
        </style>
      </defs>
      <g id="layer-1">
        <text class="cls-2" transform="translate(0 110)">
          <tspan class="cls-7" x="0" y="0">h</tspan>
          <tspan class="cls-4" x="70" y="0">e</tspan>
          <tspan class="cls-3" x="120" y="0">l</tspan>
          <tspan class="cls-4" x="150" y="0">l</tspan>
          <tspan class="cls-1" x="200" y="0">o</tspan>
          <tspan class="cls-7" x="300" y="0">w</tspan>
          <tspan x="370" y="0">o</tspan>
          <tspan class="cls-5" x="432.5" y="0">r</tspan>
          <tspan class="cls-6" x="472.5" y="0">l</tspan>
          <tspan x="520" y="0">d</tspan>
        </text>
      </g>
    </svg>
  </div>

  <div class="post-objects">
   <%= form_with(url: search_posts_path, method: :get, local: true, class: "navbar-search") do |form| %>
    <%= form.text_field :keyword, placeholder: "スレッドタイトル検索", class: "search-input", size: 25, aria: { label: "検索" } %>
    <button type="submit" class="search-btn">
      <%= image_tag 'buglens.png', alt: '検索ボタン', width: 40, height: 40, id: 'search-button' %>
    </button>
  <% end %>

    <button id="show-post-form" class="post-button">
      <p>投稿</p>
    </button>
  </div>

  <% if user_signed_in? %>
    <div class="adventure-box">
      <div class="your-status">
        <p><%= current_user.nickname %> Lv.<span class="your-level" id="your-level"><%= current_user.current_level.level_number %></span></p>
        <label for="fuel">HP: <span><%= current_user.hp%> / <%=current_user.max_hp%></span></label>
        <meter id="fuel" min="0" max= <%= current_user.max_hp %> low=<%= current_user.max_hp / 3 %>  high=<%=current_user.max_hp%> value=<%= current_user.hp %>></meter>
      </div>
      <div class="adventure">
          <%= image_tag 'adventureshoes.png', alt: '冒険の靴', class: 'shoes-image' %>
          <%= button_to '冒険', start_game_path, method: :post, class: 'start-game-btn' %>
      </div>
    </div>
  <% end %>

  <div class="navbar-links">
    <% if user_signed_in? %>
      <button class="menu-buttons">
        <%= link_to 'ログアウト', destroy_user_session_path, method: :delete %>
      </button>
      <button class="menu-buttons">
        <%= link_to 'マイページ', user_path(current_user) %>
      </button>
    <% else %>
      <button class="menu-buttons">
        <%= link_to '新規登録', new_user_registration_path, class: 'register-link' %>
      </button>
      <button class= "menu-buttons">
        <%= link_to 'ログイン', new_user_session_path, class: 'login-link' %>
      </button>
    <% end %>
      <button class="menu-buttons menu">
        メニュー
      </button>
  </div>
</nav>

app/views/shared/_level_up_modal.html.erb
<!-- app/views/shared/_level_up_modal.html.erb -->
<% if user_signed_in? %>
<div class="level-up-modal" style="display:none;">
  <div class="level-up-modal-content">
    <div class="level-up-user-name"><%=current_user.nickname%></div>
    <div class="level-up-level-up">Level up!!</div>
    <div class="level-up-message"></div>
    <div class="skill-get-message"></div>
    <div class="item-get-message"></div>
    <div class="next-experience-point-message"></div>
    <div class="required-comment-count-message"></div>
    <button class="close">とじる</button>
  </div>
</div>
<% end %>