config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }

  resources :users, only: [:show, :edit, :update]

  resources :usages, only: [:index]

  resources :games, only: [:show] do
    member do
      post 'execute_command' # コマンド実行用のルート
      post 'escape'          # 逃げるアクションのルート
      get 'result'           
    end
  end

  post 'start_game', to: 'games#start_game' # ゲーム開始用のルート


  resources :posts do
    resources :comments do
      collection do
        get 'latest'  # これにより /posts/:post_id/comments/latest のルートが作成されます
      end
    end
    collection do
      get 'search'
      get 'latest'
    end
  end

  resources :direct_message_requests, only: [:create] do
    member do
      patch :approve
      patch :reject
    end
  end
  
  # 既存のnotificationsに追加
  resources :notifications, only: [] do
    member do
      patch 'mark_as_read'
    end
    collection do
      patch 'approval', to: 'notifications#create_approval_notification'
      patch 'rejection', to: 'notifications#create_rejection_notification'
    end
  end

  resources :rooms do
    resources :messages, only: [:create] # ここで messages リソースをネスト
  end


  root to: "posts#index"
end

app/models/room.rb
# app/models/room.rb
class Room < ApplicationRecord
  has_many :messages
  has_many :room_users
  has_many :users, through: :room_users

  def receiver_user(current_user)
    # ルーム内の他のユーザーを取得
    users.where.not(id: current_user.id).first
  end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def show
    @room = Room.find(params[:id])
    @messages = @room.messages.order(created_at: :asc)
    @message = Message.new
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/show.html.erb
<div class="message-container">
  <div class="message-header">
    <%= link_to 'マイページに戻る', user_path(current_user), class: "post-top-button" %>
  </div>

  <div class="message-wrapper" data-room-id="<%= @room.id %>" data-current-user-id="<%= current_user.id %>">
    <div class="message-box">
      <% @messages.each do |message| %>
        <%= render partial: 'messages/message', locals: { message: message, current_user: current_user } %>
      <% end %>
    </div>
  </div>


  <div class="message-submit-box">
    <%= form_with(model: @message, url: room_messages_path(@room), class: "message-form-box", remote: true) do |form| %>
      <%= form.text_area :content, class: "message-text-area", placeholder: "メッセージを入力..." %>
      <%= form.submit '送信', class: "message-submit-button" %>
    <% end %>
  </div>
</div>