config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }

  resources :users, only: [:show, :edit, :update]

  resources :usages, only: [:index]

  resources :games, only: [:show] do
    member do
      post 'execute_command' # コマンド実行用のルート
      post 'escape'          # 逃げるアクションのルート
      get 'result'           
    end
  end

  post 'start_game', to: 'games#start_game' # ゲーム開始用のルート


  resources :posts do
    resources :comments do
      collection do
        get 'latest'  # これにより /posts/:post_id/comments/latest のルートが作成されます
      end
    end
    collection do
      get 'search'
      get 'latest'
    end
  end

  resources :direct_message_requests, only: [:create] do
    member do
      patch :approve
      patch :reject
    end
  end
  
  # 既存のnotificationsに追加
  resources :notifications, only: [] do
    member do
      patch 'mark_as_read'
    end
    collection do
      patch 'approval', to: 'notifications#create_approval_notification'
      patch 'rejection', to: 'notifications#create_rejection_notification'
    end
  end

  resources :rooms do
    resources :messages, only: [:create] # ここで messages リソースをネスト
  end


  root to: "posts#index"
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  has_many :comments, dependent: :destroy

  validates :title, presence: true
  validates :content, presence: true, unless: :was_attached?

  def was_attached?
    self.image.attached?
  end

  def image_url
    Rails.application.routes.url_helpers.rails_blob_url(self.image, only_path: true) if image.attached?
  end

  scope :search, -> (query) {
    if query.present?
      where('title LIKE :query', query: "%#{sanitize_sql_like(query)}%")
    else
      all
    end
  }
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all.order(created_at: :desc)
    @post = Post.new
  
    respond_to do |format|
      format.html # HTML形式のレスポンス（通常のビューが必要）
       format.json { render json: @posts }
    end
  end
  
  def search
    @posts = Post.search(params[:keyword])
  end

  def latest
    # 最新の投稿を取得 (例: 直近10件)
    latest_posts = Post.order(created_at: :desc).limit(10)
    # 必要なデータだけを返す
    render json: latest_posts.as_json(include: { user: { only: [:id, :nickname] } }, methods: [:image_url])
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user || User.guest
  
    respond_to do |format|
      if @post.save
        format.json { render json: @post.as_json(include: { user: { only: [:id, :nickname] } }, methods: [:image_url]), status: :created }
      else
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    @post = Post.find_by(id: params[:id]) # find_byを使用
    if @post.nil?
      render 'not-found', status: :not_found
      return
    end
    @comments = @post.comments.includes(:user)
    @comment = Comment.new
    @from_my_page = params[:from] == 'mypage'

    respond_to do |format|
      format.html
      format.json { render json: { post: @post, comments: @comments } }
    end
  end
  
  def edit
    @post = Post.find(params[:id])
    
    respond_to do |format|
      format.html # 通常のHTMLリクエスト
      format.json { render json: { form: render_to_string(partial: 'edit-form', locals: { post: @post }, formats: [:html]) } }
    end
  end
  
  def update
    @post = Post.find(params[:id])
  
    time_difference = Time.current - @post.created_at
  
    if time_difference > 600
      respond_to do |format|
        format.json { render json: { error: '投稿の編集期限が切れています。' }, status: :forbidden }
      end
      return
    end
  
    if @post.user.id != (current_user&.id || User.guest.id)
      respond_to do |format|
        format.json { render json: { error: 'この投稿の編集権限がありません。' }, status: :forbidden }
      end
      return
    end
  
    if @post.update(post_params)
      respond_to do |format|
        format.json { render json: { message: '投稿が更新されました。', post: @post }, status: :ok }
      end
    else
      respond_to do |format|
        format.json { render json: { errors: @post.errors.full_messages }, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post = Post.find(params[:id])
  
    # 投稿の作成時間と現在の時間の差を計算
    time_difference = Time.current - @post.created_at
  
    # 30分(1800秒)以内かどうかをチェック

    if time_difference <= 1800 && @post.user.id == (current_user&.id || User.guest.id)
      if @post.destroy
        flash[:notice] = "投稿が削除されました。"
        redirect_to root_path
      else
        flash[:alert] = "投稿の削除に失敗しました。再試行してください。"
        redirect_back(fallback_location: post_path(@post.id))
      end
    else
      flash[:alert] = "投稿は投稿したユーザーかつ30分以内にしか削除できません。"
      redirect_back(fallback_location: post_path(@post.id))
    end
    
  end
  


  private

  def post_params
    params.require(:post).permit(:title, :content, :image).merge(user_id: current_user&.id || User.guest.id)
  end
  
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_edit-form.html.erb
<%= form_with model: post, url: post_path(post), local: true, html: { id: 'edit-form' } do |f| %>
  <div class="form-group">
    <%= f.label :title, "タイトル" %>
    <%= f.text_field :title, class: 'form-title-control' %>
  </div>
  
  <div class="form-group">
    <%= f.label :content, "本文" %>
    <%= f.text_area :content, class: 'form-content-control' %>
  </div>
  
  <div class="custom-file-upload">
    <%= f.file_field :image, accept: "image/*,video/*", style: "display: none;", class: "media-file-post" %>
    <div class="file-upload-image">
    <%= f.label :image do %>
      <%= image_tag "camera.png", alt: "Upload Image", class: "custom-upload-button" %>
    <% end %>
    </div>

  <div class="form-button">
    <%= f.submit '編集する', class: 'post-button-complete' %>
  </div>
  </div>

<% end %>

app/views/posts/_form.html.erb
<%= form_with model: post, url: posts_path, remote: true, html: { id: 'post-form' } do |f| %>
  <div class="form-group">
    <%= f.label :title, "タイトル" %>
    <%= f.text_field :title, class: 'form-title-control' %>
  </div>
  <div class="form-group">
    <%= f.label :content, "本文" %>
    <%= f.text_area :content, class: 'form-content-control' %>
  </div>
  <div class="custom-file-upload">
    <%= f.file_field :image, accept: "image/*,video/*", style: "display: none;", class: "media-file-post" %>
    <div class="file-upload-image">
      <%= image_tag "camera.png", alt: "Upload Image", class: "custom-upload-button" %>
    </div>

    <div class="form-button">
      <%= f.submit '投稿する', class: 'post-button-complete' %>
    </div>
    </div>
<% end %>

app/views/posts/index.html.erb
<body class="index-page">
<%= render 'shared/level_up_modal' %>

<%= render "shared/header" %>

<div id="posts-list">
  <div id="menu">
    <span class="menu-close-button">&times;</span>
    <nav>
      <ul>
        <li><a href="#">HOME</a></li>
        <li><a href="#">ABOUT</a></li>
        <li><%= link_to '掲示板の使い方', usages_path, class: 'usages-link' %></li>
      </ul>
    </nav>
  </div>

  <% @posts.each do |post| %>
    <div class="post" id="post-box" data-post-id="<%= post.id %>">
      <div class="post-title-box">
        <h2> <%= link_to "#{post.title}", post_path(post.id), class: 'post-title-link' %> </h2>
      </div>

      <div class="post-contents-media">
      <% if post.content.present? %>
        <div class="post-content-box">
          <p><%= truncate(post.content, length: 300, omission: ' (続く...)') %></p>
        </div>
      <% end %>

      <% if post.image.attached? %>
        <div class="post-media-box">
          <%= image_tag post.image.variant(resize: '320x320').processed, class: 'post-media' %>
        </div>
      <% end %>
      </div>


      <div class="poster">
        <%= link_to "by #{post.user.nickname}", user_path(post.user, from: 'nickname'), class: 'post-user-link'%>
        <br>
        <%= l post.created_at %> <!-- 投稿日時の表示 -->
      </div>
    </div>
  <% end %>
</div>


<!-- モーダルウィンドウ -->
<div id="post-form-modal" style="display: none;">
  <div class="post-modal-content">
    <span class="close-button">&times;</span>
    <!-- 部分テンプレートを使ってフォームを表示 -->
    <div class="modal-body">
    <%= render 'form', post: @post %>
    </div>
  </div>
</div>

<%= render "shared/footer" %>

</body>

app/views/posts/not-found.html.erb
<body class="search-page">
  <%= render 'shared/level_up_modal' %>
  <div class="back-to-post-page">
    <%= link_to "Top画面へ", root_path, class: "post-top-button" %>
  </div>

 
  <div class="search-container">
    <p class="cant-find-query">スレッドが見つからないよ </p>
    <div class="green-dig-dig">
      <%= image_tag 'greenmoguri.png', alt: 'スレッドが見つからないキャラクターイメージ', class:" green-dig-man", id: 'green-moguri' %>
    </div>
  </div>

  <%= render "shared/footer" %>
</body>

app/views/posts/search.html.erb
<body class="search-page">
  <%= render 'shared/level_up_modal' %>
  <div class="back-to-post-page">
    <%= link_to "Top画面へ", root_path, class: "post-top-button" %>
  </div>

  <% if @posts.present? %>
    <div id="posts-list">
      <% @posts.each do |post| %>
        <div class="post" id="post-box">
          <div class="post-title-box">
            <h2>
              <%= link_to post.title, post_path(post.id), class: 'post-title-link' %>
            </h2>
          </div>

          <div class="post-contents-media">
            <% if post.content.present? %>
              <div class="post-content-box">
                <p><%= truncate(post.content, length: 300, omission: ' (続く...)') %></p>
              </div>
            <% end %>

            <% if post.image.attached? %>
              <div class="post-media-box">
                <%= image_tag post.image.variant(resize: '320x320').processed, class: 'post-media' %>
              </div>
            <% end %>
          </div>

          <div class="poster">
            <%= link_to "by #{post.user.nickname}", user_path(post.user, from: 'nickname'), class: 'post-user-link'%>
            <br>
            <%= l post.created_at %> <!-- 投稿日時の表示 -->
          </div>
        </div>
      <% end %>
    </div>
  <% else %>
  <div class="search-container">
    <p class="cant-find-query">スレッドが見つからないよ </p>
    <div class="green-dig-dig">
      <%= image_tag 'greenmoguri.png', alt: 'スレッドが見つからないキャラクターイメージ', class:" green-dig-man", id: 'green-moguri' %>
    </div>
  </div>
  <% end %>

  <%= render "shared/footer" %>
</body>

app/views/posts/show.html.erb
<body class="show-page">
  <!-- 残りのHTMLコンテンツ -->
  <% if @from_my_page %>
    <div class="back-to-my-page">
      <%= link_to 'マイページに戻る', user_path(current_user), class: "post-top-button" %>
    </div>
  <% else %>
    <div class="back-to-post-page">
      <%= link_to "Top画面へ", root_path, class: "post-top-button" %>
    </div>
  <% end %>

  <div id="posts-list">
    <div class="post" id="post-box">
      <!-- 画像ホバー時に変更される画像のタグ -->
      <% if @post.user && @post.user.id == (current_user&.id || User.guest.id) %>
        <%= image_tag "meat-bomb1.png", alt: "meatballmenu image", class: "meatball-menu-image", id: "hover-bomb-image2" %>
      <% end %>
      

      <div class="post-title-box">
        <h2><%= @post.title %></h2>
      </div>

      <!-- コンテンツとメディアを含むセクション -->
      <div class="post-contents-media">
        <% if @post.content.present? %>
          <div class="post-content-box">
            <p><%= @post.content %></p>
          </div>
        <% end %>

        <% if @post.image.attached? %>
          <div class="post-media-box">
            <%= image_tag @post.image.variant(resize: '320x320').processed, class: 'post-media' %>
          </div>
        <% end %>
      </div>

      <!-- 投稿者情報 -->
      <div class="poster">
        <%= link_to "by #{@post.user.nickname}", user_path(@post.user, from: 'nickname'), class: 'post-user-link' %>
        <br>
        <%= l @post.created_at %> <!-- 投稿日時の表示 -->
      </div>
    </div>

    <div id="comments-container">
    <% @post.comments.each do |comment| %>
      <div class="comment" data-comment-id="<%= comment.id %>">

        <div class="comment-content-box">
          <p><%= comment.content %></p>
        </div>

        

        <div class="commenter">
          <%= link_to "by #{comment.user.nickname}", user_path(comment.user, from: 'nickname'), class: 'post-user-link' %>
          <br>
          <%= l comment.created_at %> <!-- 投稿日時の表示 -->
        </div>

        <% if comment.user && comment.user.id == (current_user&.id || User.guest.id) %>
          <%= image_tag "meat-bomb1.png", alt: "meatballmenu image", class: "meatball-menu-image hover-bomb-image", data: { comment_id: comment.id } %>
        <% end %>

        <div class="comment-edit-delete-modal-buttons" data-comment-id="<%= comment.id %>">
          <% if comment.edit_count < 1 %>
            <button class="edit-comment-button" data-comment-id="<%= comment.id %>" data-post-id="<%= @post.id %>">Edit</button>
          <% end %>
          <button class="delete-comment-button" data-comment-id="<%= comment.id %>" data-post-id="<%= @post.id %>">Delete</button>
        </div>

        <div class="edit-comment-modal" data-comment-id="<%= comment.id %>">
          <div class="comment-content">
            <!-- モーダルウィンドウを閉じるためのボタン -->
            <span class="close-modal-button">&times;</span>

            <!-- Ajaxで読み込まれる編集フォームをここに表示 -->
            <div class="edit-comment-body" data-comment-id="<%= comment.id %>">
              <!-- ここに部分テンプレートが挿入される -->
            </div>
          </div>
        </div>

        <div class="delete-comment-modal" data-comment-id="<%= comment.id %>">
          <div class="comment-delete-box">
            <div class="delete-details">
              ※コメント内容を編集できるのは10分以内の一回のみ。削除できるのは投稿から30分以内までです。
            </div>
            <%= link_to '削除', post_comment_path(@post.id, comment.id), data: { turbo_method: :delete }, class: 'delete-comment-link' %>
            <button class="cancel-complete-button delete-cancel">キャンセル</button>
          </div>
        </div>
      </div>
    <% end %>
    </div>

    <!-- モーダルボタン -->
    <div id="modal-buttons">
      <button id="edit-thread-btn" class="edit-button" data-post-id="<%= @post.id %>">編集</button>
      <button id="delete-thread-btn" class="delete-button">削除</button>
    </div>
  </div>

  <div class="add-comment">
    <button id="add-comment-button">
      ＋コメント追加
    </button>
  </div>

  <div id="comment-modal-window" >
    <div class="comment-content">
      <!-- モーダルウィンドウを閉じるためのボタン -->
      <span class="close-modal-button">&times;</span>

      <!-- 部分テンプレートを使ってフォームを表示 -->
      <div class="comment-body">
        <%= form_with model: [ @post, @comment], id: 'comment-form', data: { turbo: false } do |f| %>
         <%= hidden_field_tag 'post_id', @post.id %>
          <div class="comment-form-group">
           <%= f.label :content, "コメント" %>
            <%= f.text_area :content, class: 'comment-content-form' %>
          </div>
          <div class="comment-form-button">
            <%= f.submit '送信', class: 'comment-submit-button' %>
          </div>
        <% end %>

      </div>
    </div>
  </div>

  <!-- モーダルウィンドウ -->
  <div id="edit-form-modal">
    <div class="edit-modal-content">
      <!-- モーダルウィンドウを閉じるためのボタン -->
      <span class="close-modal-button">&times;</span>
      <!-- 部分テンプレートを使ってフォームを表示 -->
      <div class="edit-modal-body">
        <%= render 'edit-form', post: @post %>
      </div>
    </div>
  </div>

  <div id="delete-modal">
    <div class="post-delete-box">
      <div class="delete-details">
        ※スレッド内容を編集できるのは10分以内。削除できるのは投稿から30分以内までです。
      </div>
      <button class="delete-post">
        <%= link_to '削除', post_path(@post.id), data: { turbo_method: :delete } %>
      </button>
      <button id="cancel-complete-button" class="delete-cancel">キャンセル</button>
    </div>
  </div>

  <!-- JavaScript: 画像ホバー時に画像を変更 -->
  <script>
    document.addEventListener("turbo:load", function() {
      const hoverImage = document.getElementById("hover-bomb-image2");
      const modalButtons = document.getElementById("modal-buttons");

      if (!hoverImage || !modalButtons) return;

      let hoverTimer;
      let hoverTime = 0;

      const images = [
        "<%= asset_path('meat-bomb1.png') %>", 
        "<%= asset_path('meat-bomb2.png') %>", 
        "<%= asset_path('meat-bomb3.png') %>", 
        "<%= asset_path('meat-bomb4.png') %>", 
        "<%= asset_path('meat-bomb5.png') %>", 
        "<%= asset_path('meat-bomb6.png') %>", 
        "<%= asset_path('meat-bomb7.png') %>", 
        "<%= asset_path('meat-bomb8.png') %>", 
        "<%= asset_path('meat-bomb9.png') %>", 
        "<%= asset_path('meat-bomb10.png') %>"
      ];

      hoverImage.addEventListener("mouseover", function() {
        hoverTimer = setInterval(() => {
          hoverTime += 1000; // 1秒ごとに時間を加算
          const imageIndex = Math.floor(hoverTime / 1000); // 時間に応じてインデックスを計算
          if (imageIndex < images.length) {
            hoverImage.src = images[imageIndex]; // インデックスに対応する画像に切り替える
          }
        }, 1000); // 1秒ごとにチェック
      });

      hoverImage.addEventListener("mouseout", function() {
        clearInterval(hoverTimer); // hoverが外れたらタイマーをクリア
        hoverTime = 0; // 時間をリセット
        hoverImage.src = images[0]; // 最初の画像に戻す
      });
    });
  </script>
   <%= render 'shared/level_up_modal' %>
</body>